### ISSUE TITLE
Clusterize list fails on: "Too many open files"

### ISSUE THREAD

**Issue by gimlidc** [jakub-tucek/clusterize#1]
After several "successful runs" I have obtained this error:

gimli@alfrid igre]$ clusterize list
[2019-09-15 22:38:49] [ERROR] Main:27 - Running app failed
java.nio.file.FileSystemException: /auto/plzen1/home/gimli/igre/./data/processed/metacentrum/04-registration-experiment/outs/task-26__2019-09-12_19-54-02/5100: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_60]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_60]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_60]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[?:1.8.0_60]
	at java.nio.file.Files.newDirectoryStream(Files.java:457) ~[?:1.8.0_60]
	at java.nio.file.Files.list(Files.java:3451) ~[?:1.8.0_60]
	at cz.fit.metacentrum.util.JobUtils.updateAsFailedJob(JobUtils.kt:14) ~[metacentrum-cli.jar:?]
	at cz.fit.metacentrum.service.action.status.ex.JobStatusCheckExecutor.execute(JobStatusCheckExecutor.kt:21) ~[metacentrum-cli.jar:?]
	at cz.fit.metacentrum.service.action.status.MetadataStatusService.updateMetadataState(MetadataStatusService.kt:48) ~[metacentrum-cli.jar:?]
	at cz.fit.metacentrum.service.action.status.ActionStatusService.processAction(ActionStatusService.kt:35) ~[metacentrum-cli.jar:?]
	at cz.fit.metacentrum.service.action.status.ActionStatusService.processAction(ActionStatusService.kt:15) ~[metacentrum-cli.jar:?]
	at cz.fit.metacentrum.service.MainService.execute(MainService.kt:36) ~[metacentrum-cli.jar:?]
	at cz.fit.metacentrum.MainKt.main(Main.kt:23) [metacentrum-cli.jar:?]
/auto/plzen1/home/gimli/igre/./data/processed/metacentrum/04-registration-experiment/outs/task-26__2019-09-12_19-54-02/5100: Too many open files

For simulation I recommend several (6) clusterized runs with 7k tasks. It seems, that there is more than 65535 files in the list checked by clusterize. Probably cleanup of history runs will help (but not tested).

**Comment by jakub-tucek** [comment]
I was unable to simulate bug on my local system, where the limit for max open files is much higher.

Nonetheless, I found a code that did not close files when listing them, which was probably the source of the issue. Changes are released under version 0.14 (https://github.com/jakub-tucek/clusterize/releases/tag/v0.14)

Installation to the newest version can be done using the following command:

`$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/jakub-tucek/metacentrum-cli/master/src/scripts/install.sh) v0.14"`


Can you please try if it helped?

**Comment by gimlidc** [comment]
Fixed
