### ISSUE TITLE
Smazaný metadata dir

### ISSUE THREAD

**Issue by gimlidc** [jakub-tucek/clusterize#3]
Pokud smažu storage metadat, nemusely by se jen úlohy v listu objevit. Místo toho clusterize žuchne:

 --- Folder /storage/plzen1/home/gimli/.clusterize/metadataStorage/task-36__2019-11-28_15-00-15 does not contain metadata file
 --- Folder /storage/plzen1/home/gimli/.clusterize/metadataStorage/task-34__2019-10-25_11-03-38 does not contain metadata file
[2019-12-17 10:16:31] [ERROR] Main:27 - Running app failed
java.nio.file.NoSuchFileException: /auto/plzen1/home/gimli/igre/../40-shift-rotation-scale/storage/task-42__2019-12-16_10-18-14/0
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_60]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_60]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_60]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[?:1.8.0_60]
	at java.nio.file.Files.newDirectoryStream(Files.java:457) ~[?:1.8.0_60]
	at java.nio.file.Files.list(Files.java:3451) ~[?:1.8.0_60]
	at cz.fit.metacentrum.util.JobUtils.updateAsFailedJob(JobUtils.kt:14) ~[clusterize.jar:?]
	at cz.fit.metacentrum.service.action.status.ex.CheckQueueExecutor.updateJobState(CheckQueueExecutor.kt:64) ~[clusterize.jar:?]
	at cz.fit.metacentrum.service.action.status.ex.CheckQueueExecutor.execute(CheckQueueExecutor.kt:34) ~[clusterize.jar:?]
	at cz.fit.metacentrum.service.action.status.MetadataStatusService.updateMetadataState(MetadataStatusService.kt:47) ~[clusterize.jar:?]
	at cz.fit.metacentrum.service.action.status.ActionStatusService.processAction(ActionStatusService.kt:35) ~[clusterize.jar:?]
	at cz.fit.metacentrum.service.action.status.ActionStatusService.processAction(ActionStatusService.kt:15) ~[clusterize.jar:?]
	at cz.fit.metacentrum.service.MainService.execute(MainService.kt:36) ~[clusterize.jar:?]
	at cz.fit.metacentrum.MainKt.main(Main.kt:23) [clusterize.jar:?]
/auto/plzen1/home/gimli/igre/../40-shift-rotation-scale/storage/task-42__2019-12-16_10-18-14/0

**Comment by jakub-tucek** [comment]
Clarification: Error occurs when metadata file points to storage directory that does not exists and therefore cannot update job status - which is bug.


@gimlidc 

Fixed in:

```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/jakub-tucek/metacentrum-cli/master/src/scripts/install.sh) v0.15"
```
